//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HFProtocol.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDC_EDIT_FILE                   101
#define IDS_OUT_VIEW                    102
#define ID_VIEW_OUT                     103
#define IDS_DEMODE_VIEW                 104
#define ID_VIEW_DEMODE                  105
#define IDS_RECOGNIZE_VIEW              106
#define ID_VIEW_RECOGNIZE               107
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_HFsysTYPE                   130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define IDS_FILE_VIEW                   155
#define IDS_ADCTR_VIEW                  156
#define IDS_ANDVT_VIEW                  157
#define IDS_CLEW_VIEW                   158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDR_HFANALYSES                  179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_ANDVTVIEW               219
#define ID_VIEW_CLEWVIEW                220
#define ID_VIEW_DETECT                  221
#define IDS_DETECT_VIEW                 222
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_HFANALYSEVIEW               310
#define IDD_PLAYPANEVIEW                312
#define IDD_DIALOG1                     314
#define IDD_DIALOG_CLEW                 314
#define IDD_DLG_PLAY                    315
#define IDB_STOPBACK                    316
#define IDB_PLAY                        317
#define IDB_STOP                        318
#define IDB_CONTINUE                    319
#define IDD_FORMAT                      324
#define IDS_PLAYPANE_VIEW               326
#define ID_VIEW_PLAYPANE                327
#define IDC_EDIT_FILE_TREE              327
#define IDB_PNG2                        333
#define IDB_BACKTOBEGIN                 333
#define IDB_PNG3                        334
#define IDB_PNG4                        335
#define IDB_PNG5                        336
#define IDB_PNG6                        337
#define IDI_ICON_FORWARD                338
#define IDI_ICON_GOTOEND                340
#define IDI_ICON_GOTOBEGIN              341
#define IDI_ICON_PLAYTOEND              342
#define IDI_ICON_PAUSE                  343
#define IDI_ICON_BACKWARD               344
#define IDI_ICON_STOP                   345
#define IDI_ICON_PLAY                   348
#define IDD_DIALOG_RECOGNIZE            349
#define IDD_DIALOG_DEMODE               350
#define IDC_EDIT1                       1013
#define IDC_INSAMPLE                    1013
#define IDC_SAMPLERATE                  1013
#define IDC_EDIT_SEL_BEGIN              1013
#define IDC_FILEOPEN                    1014
#define IDC_OUTSAMPLE                   1014
#define IDC_EDIT2                       1014
#define IDC_EDIT_SHOW_BEGIN             1014
#define IDC_BUTTON1                     1015
#define IDC_FILEDEMODE                  1015
#define IDC_EDIT3                       1015
#define IDC_EDIT_SEL_END                1015
#define IDC_FILEFC                      1016
#define IDC_EDIT4                       1016
#define IDC_EDIT_SHOW_END               1016
#define IDC_FILEBAUD                    1017
#define IDC_EDIT5                       1017
#define IDC_EDIT_SEL_LENGTH             1017
#define IDC_FREDEC                      1018
#define IDC_MAG                         1018
#define IDC_EDIT6                       1018
#define IDC_EDIT_SHOW_LENGTH            1018
#define IDC_ANDVT_FC5                   1020
#define IDC_ORDER                       1020
#define IDC_ANDVT_FC6                   1021
#define IDC_BUTTON_STOPBACK             1026
#define IDC_BUTTON_PLAY                 1027
#define IDC_BUTTON_START                1028
#define IDC_SHOWTIME                    1028
#define IDC_BUTTON_CONTINUE             1029
#define IDC_BUTTON_PLAYTOEND            1029
#define IDC_BUTTON_STOP                 1030
#define IDC_BUTTON_PAUSE                1030
#define IDC_BUTTON_GOTOBEGIN            1032
#define IDC_BUTTON_BACKWARD             1033
#define IDC_BUTTON_FORWARD              1034
#define IDC_BUTTON_GOTOEND              1035
#define IDC_COMBO_FILETYPE              1079
#define IDC_BUTTON2                     1080
#define IDC_DETECT                      1080
#define IDC_FILE_PROGRESS               1081
#define IDC_PROTOCAL                    1082
#define IDC_COMBO_PROTOCOL              1083
#define IDC_DETECT5                     1084
#define IDC_CONSTE                      1085
#define IDC_LISTSAMPLERATE              1088
#define IDC_RADIOMONO                   1089
#define IDC_RADIOSTEREO                 1090
#define IDC_CHECK_ALL                   1090
#define IDC_RADIO3                      1091
#define IDC_RADIO16BIT                  1091
#define IDC_CHECK_110A                  1091
#define IDC_CHECK_110B                  1092
#define IDC_CHECK_SLEW                  1093
#define IDC_CHECK_141A                  1093
#define IDC_CHECK_141BTLC               1094
#define IDC_CHECK_141B                  1094
#define IDC_CHECK_141BBW0               1095
#define IDC_CHECK_LINK11SLEW            1095
#define IDC_CHECK_141BBW1               1096
#define IDC_CHECK_LINK11CLEW            1096
#define IDC_CHECK_141BBW3               1097
#define IDC_CHECK_PSK                   1097
#define IDC_CHECK_4285                  1098
#define IDC_CHECK_4529                  1099
#define IDC_THREOD1                     1100
#define IDC_SPIN_TH1                    1101
#define IDC_THREOD2                     1102
#define IDC_CHECK_FSK                   1102
#define IDC_SPIN_TH2                    1103
#define IDC_CHECK_OFDM                  1103
#define IDC_COMBO_DATARATE              1106
#define IDC_COMBO_FEC                   1107
#define IDC_COMBO3                      1108
#define IDC_COMBO_INTRE                 1108
#define IDC_DEMODE                      1110
#define IDC_FILE_PROGRESS2              1111
#define IDC_SAMPLE                      1112
#define IDC_PROPLIST_POSITION           1160
#define IDC_COMBO_SIGTYPE               1161
#define IDC_RADIO_KONGSHOU              1163
#define IDC_CHECK_DEMODE                1164
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_OPENHFSYS                    32773
#define ID_OPENHFHIST                   32774
#define IDM_OPENDATA                    32775
#define ID_CLOSEANA                     32776
#define ID_Menu                         32777
#define ID_32778                        32778
#define ID_32779                        32779
#define ID_Menu32780                    32780
#define ID_32781                        32781
#define ID_SET_FILEPATH                 32782
#define ID_32783                        32783
#define ID_32784                        32784
#define ID_PLAY                         32785
#define ID_32786                        32786
#define ID_STOP                         32787
#define ID_32788                        32788
#define ID_CONTINUE                     32789
#define ID_32790                        32790
#define ID_STOPBACK                     32791

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        351
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         1113
#define _APS_NEXT_SYMED_VALUE           313
#endif
#endif
